name = "failtrack-api"
# type = "javascript"
account_id = "53a9cb10660f9c0afdd4c6d8acaaa635
workers_dev = true
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "failtrack"
database_id = "19daf170-81e3-405a-a3b5-87dff0dc9e0a"

[env.production]
workers_dev = false
route = "https://failtrack.example.com/api/*" 

[assets]
directory = "dist"
